spring:
  application:
    name: auth-service
  config:
    import: ${CONFIG_SERVER_IMPORT:optional:configserver:http://localhost:8888}
#  cloud:
#    config:
#      fail-fast: true
#      enabled: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
#
keycloak:
  serverUrl: http://keycloak:8080
  realm: spring-boot-microservices-realm
  clientId: spring-cloud-client
  clientSecret: gateway-secret
