version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8090"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

###  Zipkin
#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#       - "9411:9411"
#
###  Eureka Server
#  eureka-server:
#    image: arseniolourenco/discovery-server:latest
#    container_name: discovery-server
##    pull_police: always
#    ports:
#      - "8761:8761"
##    environment:
##      -SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - zipkin

#  accounts-service:
#    image: your-dockerhub-username/accounts-service
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
#    ports:
#      - "8081:8081"
#    depends_on:
#      - eureka-server

## MySQL Docker Compose Config
#  mysql:
#    image: mysql:latest
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root  # Set the root password
#      MYSQL_DATABASE: inventory-service          # Optional: specify a default database
#      MYSQL_USER: admin                    # Optional: create a new user
#      MYSQL_PASSWORD: admin       # Optional: password for the new user
#    ports:
#      - "3306:3306"  # Expose MySQL port
#    volumes:
#      - mysql_data:/var/lib/mysql  # Persist data
#    networks:
#      - mysql_network
#
#volumes:
#    mysql_data:
#
#networks:
#    mysql_network:

