CREATE DATABASE IF NOT EXISTS keycloakDB;
CREATE DATABASE IF NOT EXISTS inventoryDB;

GRANT ALL PRIVILEGES ON keycloakDB.* TO 'mauro'@'%';
GRANT ALL PRIVILEGES ON inventoryDB.* TO 'mauro'@'%';

CREATE USER IF NOT EXISTS 'mauro'@'%' IDENTIFIED BY 'mauro007';
GRANT ALL PRIVILEGES ON *.* TO 'mauro'@'%';

FLUSH PRIVILEGES;