
# ===   CONFIG CLIENT   ===
spring.application.name=${USER_SERVICE_NAME:user-service}
spring.config.import=${CONFIG_SERVER_IMPORT:optional:configserver:http://config-server:8888}
spring.cloud.config.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/spring-boot-microservices-realm