spring.application.name=user-service
spring.config.import=${CONFIG_SERVER_IMPORT:optional:configserver:http://localhost:8888}
spring.cloud.config.fail-fast=true
spring.cloud.config.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/spring-boot-microservices-realm
