#eureka.instance.instance-id=${spring.application.name}:${server.port}
#eureka.instance.preferIpAddress=true
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.enabled=true
#eureka.client.healthcheck.enabled=true
#management.endpoints.web.exposure.include=*
#management.endpoints.health.show-details=always
#
## ? Configure logging pattern to include traceId and spanId for better traceability
#logging.pattern.level=%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]