##   === APPLICATION CONFIGURATION ===
#server.port=${CONFIG_SERVER_PORT}
#spring.application.name=${CONFIG_SERVER_NAME}
#
##   === GITHUB REPOSITORY CONFIG ===
#spring.cloud.config.server.git.uri=${CONFIG_SERVER_URI}
#spring.cloud.config.server.git.username=${GIT_USERNAME}
#spring.cloud.config.server.git.password=${GIT_KEY}
#spring.cloud.config.server.git.default-label=${CONFIG_SERVER_DEFAULT_LABEL}
#spring.cloud.config.server.git.clone-on-start=true