name: Build
on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ }}

jobs:
  build:
    strategy:
      matrix:
        image_name: ["order", "product", "inventory"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 22
          distribution: "corretto"

      - name: Build
        working-directory: ${{ matrix.image_name }}
        run: |
         ./maven bootJar
          mv build/libs/$(ls build/libs) app.jar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}