#name: Build and Deploy Microservices
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#env:
#  REGISTRY: ghcr.io
#  REPO_OWNER: ${{ github.repository_owner }}
#
#jobs:
#  build:
#    strategy:
#      matrix:
#        service: ["api-gateway", "discovery-server", "order-service", "product-service", "inventory-service", "notification-service"]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      - name: Set Up JDK 22
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: '22'
#          cache: maven
#
#      - name: Build Maven Project
#        run: mvn clean install -DskipTests
#
#      - name: Run Tests
#        run: mvn test
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Build and Push Docker Image for ${{ matrix.service }}
#        working-directory: ${{ matrix.service }}
#        run: |
#          docker build -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}:latest .
#          docker push ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}:latest

name: Build and Deploy Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    strategy:
      matrix:
        service: ["api-gateway", "discovery-server", "order-service", "product-service", "inventory-service", "notification-service"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'
          cache: maven

      - name: Build Maven Project
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Submit Dependencies to GitHub
        uses: github/dependency-submission-action@v4
        with:
          working-directory: ${{ matrix.service }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image for ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}:latest .
          docker push ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}:latest